---

# - name: Read private key
#   slurp:
#     src: "{{ wireguard_path }}/privatekey"
#   register: private
#   when: wireguard_server

# - name: Read public key
#   slurp:
#     src: "{{ wireguard_path }}/publickey"
#   register: public
#   when: wireguard_server

- name: Generate configs
  template:
    src: interface.conf.j2
    dest: "{{ wireguard_path }}/{{ wireguard_network_name }}.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o="
  register: config
  notify:
    - Enable wg-quick service
    - Restart wg-quick service